-- Generated by scripts/generate-blurhashes.ts — do not edit by hand.
-- Paste these UPDATEs into a new `<timestamp>_nft_blurhash_backfill.sql`
-- migration when refreshing blurhashes after artwork changes.

UPDATE public.nfts SET blurhash = 'LGN9]~M__3^*~qxuM{R*~qxuD%NH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-egyptian' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LGN9]~M__3^*~qxuM{R*~qxuD%NH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-egyptian' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LGN9]~M__3^*~qxuM{R*~qxuD%NH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-egyptian' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LGN9]~M__3^*~qxuM{R*~qxuD%NH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-egyptian' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LgNle:xa^ixZ%1WVayof~AjGE3bH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-maya-stone' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LgNle:xa^ixZ%1WVayof~AjGE3bH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-maya-stone' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LgNle:xa^ixZ%1WVayof~AjGE3bH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-maya-stone' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LgNle:xa^ixZ%1WVayof~AjGE3bH'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'ancient-maya-stone' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj['
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'medieval-castle-garderobe' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj['
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'medieval-castle-garderobe' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj['
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'medieval-castle-garderobe' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj['
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'medieval-castle-garderobe' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LWGm[LtR*0x^%hV@WBo#yYozMdV@'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'prehistoric-stone' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LWGm[LtR*0x^%hV@WBo#yYozMdV@'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'prehistoric-stone' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LWGm[LtR*0x^%hV@WBo#yYozMdV@'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'prehistoric-stone' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LWGm[LtR*0x^%hV@WBo#yYozMdV@'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'prehistoric-stone' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LsK-I@j]-@xv%NogWAWAt9ogRiRi'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'victorian-era-wooden-throne' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LsK-I@j]-@xv%NogWAWAt9ogRiRi'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'victorian-era-wooden-throne' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LsK-I@j]-@xv%NogWAWAt9ogRiRi'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'victorian-era-wooden-throne' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LsK-I@j]-@xv%NogWAWAt9ogRiRi'
  WHERE blurhash IS NULL AND type = 'cruise-seat'::nft_type AND name = 'victorian-era-wooden-throne' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L8DAfa?a005st6xWIU9Z00I;~9#Q'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'astronaut-zero-gravity' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L6Hw#d~90NKO1OEOwJsp01EMWF$g'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'astronaut-zero-gravity' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L8B4k5-;01AJs7s%M{IU00M{~7wa'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'astronaut-zero-gravity' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L3BDW@=}000ftTx_ITbo00Eh}K;^'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'astronaut-zero-gravity' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LHL5I4tS~o^*~poeIoWD~UxZ9HIq'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'portable-construction-site-cabin' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L5HdZV~7040i08NMDjIpE}s+4@NI'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'portable-construction-site-cabin' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LM9k,N?w%gtR%2%gxut7s*xus.s:'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'portable-construction-site-cabin' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L26*B=t600N3tMogRRWB00e;~DR$'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'portable-construction-site-cabin' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LZIF-*-;%#tR%gofaykC*0azR5az'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'prehistoric-sanitation' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L6FhUr~TEMRj039cV]xa02E2$%WC'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'prehistoric-sanitation' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L67L=%~q?v%g#N%MnNjFVBj?RPV@'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'prehistoric-sanitation' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L36*US?I00D%s+j[R-of00D%~V%M'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'prehistoric-sanitation' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LEMs4f-p=Z-U?GxFV[N_}AV@E*of'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'roman-public-latrines' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L4GRLv%24,~S049a9u%300S0tTRQ'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'roman-public-latrines' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L57oey~p?v.9z,.7tQjEr9x^RNR4'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'roman-public-latrines' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LADvcn?I00jXtRM{9FWB00M{~pMy'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'roman-public-latrines' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LUN]d}oJ~V-p%Moff6WB_2t69ZRk'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'rustic-forest-outhouse' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L7GaHrNIBm~80PR,E3NI0ixYv%EN'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'rustic-forest-outhouse' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L98F7x?b%%%hvx%MoHjYROoziuRh'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'rustic-forest-outhouse' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LBKUp6S2ui_3=*xuH[RkyYt6H?M|'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'rustic-forest-outhouse' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LaI=1vozrRs?RobExZoMv[jcxooM'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'squat' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L5J@Bhwt00=_0pR:9wIV00xu_NRj'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'squat' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L8E{na.903-;{H%2Xnay00xZ_1Rj'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'squat' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'L7LO7$.80x?c{=s:D*af%hjb$kRj'
  WHERE blurhash IS NULL AND type = 'turbo-flush'::nft_type AND name = 'squat' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LNJb25og~q-;?bafIUt7-;t6IAM{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'cyberpunk-dystopian' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LNJb25og~q-;?bafIUt7-;t6IAM{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'cyberpunk-dystopian' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LNJb25og~q-;?bafIUt7-;t6IAM{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'cyberpunk-dystopian' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LNJb25og~q-;?bafIUt7-;t6IAM{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'cyberpunk-dystopian' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LHNJtDnh_4_3_3odIUo#t8t7RjMx'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'dubai' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LHNJtDnh_4_3_3odIUo#t8t7RjMx'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'dubai' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LHNJtDnh_4_3_3odIUo#t8t7RjMx'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'dubai' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LHNJtDnh_4_3_3odIUo#t8t7RjMx'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'dubai' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'eco-friendly' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'eco-friendly' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'eco-friendly' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'eco-friendly' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LAJRF1~qDV$-^,ITxaj1I0xby6M{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'futuristic-sci-fi-vacuum' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LAJRF1~qDV$-^,ITxaj1I0xby6M{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'futuristic-sci-fi-vacuum' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LAJRF1~qDV$-^,ITxaj1I0xby6M{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'futuristic-sci-fi-vacuum' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LAJRF1~qDV$-^,ITxaj1I0xby6M{'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'futuristic-sci-fi-vacuum' AND rarity = 'transcendent'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LmN,bwWB~p?H%MWBaext-;ofIVWB'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'renaissance-chaise' AND rarity = 'common'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LmN,bwWB~p?H%MWBaext-;ofIVWB'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'renaissance-chaise' AND rarity = 'legendary'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LmN,bwWB~p?H%MWBaext-;ofIVWB'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'renaissance-chaise' AND rarity = 'rare'::nft_rarity;
UPDATE public.nfts SET blurhash = 'LmN,bwWB~p?H%MWBaext-;ofIVWB'
  WHERE blurhash IS NULL AND type = 'zen-fortress'::nft_type AND name = 'renaissance-chaise' AND rarity = 'transcendent'::nft_rarity;

UPDATE public.mystery_boxes SET blurhash = 'LCGZ@eo58]=%-ss;V[S0#es;E?NF'
  WHERE blurhash IS NULL AND rarity = 'common'::nft_rarity;
UPDATE public.mystery_boxes SET blurhash = 'L38|em0K8@^*1-$*DQOU=8kBy2M|'
  WHERE blurhash IS NULL AND rarity = 'rare'::nft_rarity;
UPDATE public.mystery_boxes SET blurhash = 'LNFgh^rx52%2%3jcRlj=EDoc$[R+'
  WHERE blurhash IS NULL AND rarity = 'legendary'::nft_rarity;
UPDATE public.mystery_boxes SET blurhash = 'L5FzhY$p00=kaDoM$%WFqvs;GSIm'
  WHERE blurhash IS NULL AND rarity = 'transcendent'::nft_rarity;
