import type { Tables } from './database.types';

// Re-export all type modules
export * from './auth';
export * from './navigation';
export * from './components';
export * from './sensors';
export * from './audio';
export * from './nft';

// Database types (generated by `supabase gen types typescript`)
export type { Database, Json, Tables, TablesInsert, TablesUpdate, Enums } from './database.types';

// Canonical DB row type aliases
/** Row type for public.flush_detections — single source of truth. */
export type DetectionRecord = Tables<'flush_detections'>;

// Difficulty Modes (used across multiple features)
export type DifficultyMode = 'easy' | 'normal' | 'strict';

// NFT Sort Options (used in Vault and Marketplace)
export type SortOption = 'efficiency' | 'resilience' | 'comfort' | 'luck' | 'level';
