import { StyleSheet } from 'react-native';
import { colors, RARITY_COLORS } from '@/constants';

export const styles = StyleSheet.create({
  nftCard: {
    width: '48%',
    marginBottom: 16,
    borderRadius: 12,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
  },
  imageContainer: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: colors.bgLight,
    position: 'relative',
  },
  nftImage: {
    width: '100%',
    height: '100%',
  },
  levelBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colors.level,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  levelText: {
    color: colors.bgSurface,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  tierBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  tierText: {
    color: colors.bgSurface,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  rarityBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  rarityText: {
    color: colors.bgSurface,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  listedBadge: {
    position: 'absolute',
    top: 34,
    right: 8,
    backgroundColor: colors.buttonSuccess,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  listedText: {
    color: colors.bgSurface,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  cardContent: {
    padding: 8,
  },
  nftName: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.title,
    marginBottom: 4,
    minHeight: 32,
  },
  // Tier badge variants
  'cruise-seatBadge': { backgroundColor: RARITY_COLORS.common },
  'turbo-flushBadge': { backgroundColor: RARITY_COLORS.legendary },
  'zen-fortressBadge': { backgroundColor: colors.luck },
  // Rarity badge variants
  commonBadge: { backgroundColor: RARITY_COLORS.common },
  rareBadge: { backgroundColor: RARITY_COLORS.rare },
  legendaryBadge: { backgroundColor: RARITY_COLORS.legendary },
  transcendentBadge: { backgroundColor: RARITY_COLORS.transcendent },
});
