import { StyleSheet } from 'react-native';
import { colors } from '@/constants';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: colors.bgOverlayDarkMid,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.bgSurface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 40,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
  },
  closeButton: {
    padding: 4,
  },
  closeText: {
    fontSize: 18,
    color: colors.text,
  },
  subtitle: {
    fontSize: 13,
    color: colors.text,
    marginBottom: 20,
  },
  nftName: {
    fontSize: 13,
    color: colors.text,
    fontStyle: 'italic',
  },
  pointsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.bgLight,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  pointsLabel: {
    fontSize: 13,
    color: colors.text,
    fontWeight: '600',
  },
  pointsValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.level,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  statLabel: {
    width: 80,
    fontSize: 13,
    fontWeight: '600',
    color: colors.propertyText,
  },
  barWrapper: {
    flex: 1,
    marginHorizontal: 10,
    height: 8,
    backgroundColor: colors.propertyBg,
    borderRadius: 4,
    overflow: 'visible',
    position: 'relative',
  },
  barFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    borderRadius: 4,
  },
  barDelta: {
    position: 'absolute',
    top: 0,
    height: '100%',
    borderRadius: 4,
    opacity: 0.55,
  },
  valueText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.propertyValue,
    width: 36,
    textAlign: 'right',
  },
  adjustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  adjustBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.bgLight,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  adjustBtnDisabled: {
    opacity: 0.35,
  },
  adjustBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
    lineHeight: 20,
  },
  deltaText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.level,
    width: 28,
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: colors.buttonPrimary,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  confirmButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  confirmButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.buttonText,
  },
  laterButton: {
    flex: 1,
    backgroundColor: colors.bgLight,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  laterButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
  },
  errorText: {
    fontSize: 12,
    color: colors.error,
    textAlign: 'center',
    marginBottom: 8,
  },
});
