#!/usr/bin/env tsx
/**
 * generate-blurhashes.ts
 *
 * Generates blurhash strings for every static NFT and mystery-box image and
 * writes the lookup tables to `shared/src/blurhashes.ts`. Also emits a
 * companion SQL file at
 * `supabase/migrations/_data/nft_blurhash_backfill.sql` that UPDATEs every
 * existing row in `nfts` and `mystery_boxes` with its blurhash — paste the
 * UPDATEs into a new migration when you need to backfill after artwork changes.
 *
 * Usage:
 *   SUPABASE_URL=https://<ref>.supabase.co pnpm generate:blurhashes
 *
 * Optional env:
 *   COMPONENTS_X (default 4), COMPONENTS_Y (default 3) — blurhash detail
 *   ASSET_BASE — override storage URL prefix (default `${SUPABASE_URL}/storage/v1/object/public/assets`)
 *
 * Idempotency: re-running with no asset changes produces a no-op diff.
 */

import { writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import sharp from 'sharp'
import { encode } from 'blurhash'

import { NFT_TYPES, RARITIES, TYPE_NAMES, type NFTType, type NFTRarity } from '../shared/src/nft'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')

const SUPABASE_URL = process.env.SUPABASE_URL
if (!SUPABASE_URL) {
  console.error('SUPABASE_URL is required')
  process.exit(1)
}

const ASSET_BASE =
  process.env.ASSET_BASE ?? `${SUPABASE_URL}/storage/v1/object/public/assets`
const COMPONENTS_X = Number.parseInt(process.env.COMPONENTS_X ?? '4', 10)
const COMPONENTS_Y = Number.parseInt(process.env.COMPONENTS_Y ?? '3', 10)

interface NftAsset {
  type: NFTType
  name: string
  rarity: NFTRarity
  url: string
}

interface BoxAsset {
  rarity: NFTRarity
  url: string
}

/** Fetches a remote image and encodes it as a blurhash string. */
async function hashUrl(url: string): Promise<string> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status} ${res.statusText}`)
  const buf = Buffer.from(await res.arrayBuffer())
  // Resize to 32×32 for fast, stable hashing (blurhash is low-frequency anyway).
  const { data, info } = await sharp(buf)
    .raw()
    .ensureAlpha()
    .resize(32, 32, { fit: 'inside' })
    .toBuffer({ resolveWithObject: true })
  return encode(new Uint8ClampedArray(data), info.width, info.height, COMPONENTS_X, COMPONENTS_Y)
}

function nftAssets(): NftAsset[] {
  const out: NftAsset[] = []
  for (const type of NFT_TYPES) {
    for (const name of TYPE_NAMES[type]) {
      for (const rarity of RARITIES) {
        out.push({
          type,
          name,
          rarity,
          url: `${ASSET_BASE}/toilets/${type}/${name}/${name}-${rarity}.jpg`,
        })
      }
    }
  }
  return out
}

function mysteryBoxAssets(): BoxAsset[] {
  return RARITIES.map((rarity) => ({
    rarity,
    url: `${ASSET_BASE}/mystery-boxes/${rarity}.jpg`,
  }))
}

async function main(): Promise<void> {
  console.log(`Generating blurhashes (${COMPONENTS_X}×${COMPONENTS_Y}) from ${ASSET_BASE}`)

  const nfts = nftAssets()
  const boxes = mysteryBoxAssets()

  const nftEntries: (NftAsset & { hash: string })[] = []
  for (const a of nfts) {
    try {
      const hash = await hashUrl(a.url)
      nftEntries.push({ ...a, hash })
      console.log(`  ✓ ${a.type}/${a.name}/${a.rarity}`)
    } catch (err) {
      console.warn(`  ✗ ${a.type}/${a.name}/${a.rarity}: ${(err as Error).message}`)
    }
  }

  const boxEntries: (BoxAsset & { hash: string })[] = []
  for (const b of boxes) {
    try {
      const hash = await hashUrl(b.url)
      boxEntries.push({ ...b, hash })
      console.log(`  ✓ mystery-box/${b.rarity}`)
    } catch (err) {
      console.warn(`  ✗ mystery-box/${b.rarity}: ${(err as Error).message}`)
    }
  }

  // ── Write shared/src/blurhashes.ts ────────────────────────────────────────
  const tsPath = resolve(REPO_ROOT, 'shared/src/blurhashes.ts')
  const sortedNft = [...nftEntries].sort((a, b) =>
    `${a.type}/${a.name}/${a.rarity}`.localeCompare(`${b.type}/${b.name}/${b.rarity}`),
  )
  const nftLines = sortedNft
    .map((e) => `  '${e.type}/${e.name}/${e.rarity}': '${e.hash}',`)
    .join('\n')
  const boxLines = boxEntries
    .map((e) => `  ${e.rarity}: '${e.hash}',`)
    .join('\n')

  const ts = `/**
 * Blurhash lookup tables for static NFT and mystery-box artwork.
 *
 * Generated by \`scripts/generate-blurhashes.ts\` — DO NOT edit by hand.
 * Re-run the script whenever new artwork is added or existing artwork is
 * replaced, then commit the regenerated tables alongside the asset.
 *
 * If a key is missing the helpers return \`undefined\`; consumers fall back to
 * the solid placeholder background, so out-of-date tables never break rendering.
 */

import type { NFTRarity, NFTType } from './nft.ts'

/** Composite key used to look up an NFT blurhash: \`\${type}/\${name}/\${rarity}\`. */
export type NFTBlurhashKey = \`\${NFTType}/\${string}/\${NFTRarity}\`

export const NFT_BLURHASHES: Partial<Record<NFTBlurhashKey, string>> = {
${nftLines}
}

export const MYSTERY_BOX_BLURHASHES: Partial<Record<NFTRarity, string>> = {
${boxLines}
}

export function getNftBlurhash(
  type: NFTType,
  name: string,
  rarity: NFTRarity,
): string | undefined {
  return NFT_BLURHASHES[\`\${type}/\${name}/\${rarity}\`]
}

export function getMysteryBoxBlurhash(rarity: NFTRarity): string | undefined {
  return MYSTERY_BOX_BLURHASHES[rarity]
}
`
  await writeFile(tsPath, ts, 'utf8')
  console.log(`Wrote ${tsPath}`)

  // ── Write companion backfill SQL ──────────────────────────────────────────
  const sqlDir = resolve(REPO_ROOT, 'supabase/migrations/_data')
  await mkdir(sqlDir, { recursive: true })
  const sqlPath = resolve(sqlDir, 'nft_blurhash_backfill.sql')
  const nftSql = sortedNft
    .map(
      (e) =>
        `UPDATE public.nfts SET blurhash = '${e.hash}'\n  WHERE blurhash IS NULL AND type = '${e.type}'::nft_type AND name = '${e.name}' AND rarity = '${e.rarity}'::nft_rarity;`,
    )
    .join('\n')
  const boxSql = boxEntries
    .map(
      (e) =>
        `UPDATE public.mystery_boxes SET blurhash = '${e.hash}'\n  WHERE blurhash IS NULL AND rarity = '${e.rarity}'::nft_rarity;`,
    )
    .join('\n')
  const sql = `-- Generated by scripts/generate-blurhashes.ts — do not edit by hand.
-- Paste these UPDATEs into a new \`<timestamp>_nft_blurhash_backfill.sql\`
-- migration when refreshing blurhashes after artwork changes.

${nftSql}

${boxSql}
`
  await writeFile(sqlPath, sql, 'utf8')
  console.log(`Wrote ${sqlPath}`)

  console.log(
    `\nDone. ${nftEntries.length}/${nfts.length} NFTs, ${boxEntries.length}/${boxes.length} mystery boxes.`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
