/**
 * Blurhash lookup tables for static NFT and mystery-box artwork.
 *
 * Generated by `scripts/generate-blurhashes.ts` — DO NOT edit by hand.
 * Re-run the script whenever new artwork is added or existing artwork is
 * replaced, then commit the regenerated tables alongside the asset.
 *
 * If a key is missing the helpers return `undefined`; consumers fall back to
 * the solid placeholder background, so out-of-date tables never break rendering.
 */

import type { NFTRarity, NFTType } from './nft.ts'

/** Composite key used to look up an NFT blurhash: `${type}/${name}/${rarity}`. */
export type NFTBlurhashKey = `${NFTType}/${string}/${NFTRarity}`

export const NFT_BLURHASHES: Partial<Record<NFTBlurhashKey, string>> = {
  'cruise-seat/ancient-egyptian/common': 'LGN9]~M__3^*~qxuM{R*~qxuD%NH',
  'cruise-seat/ancient-egyptian/legendary': 'LGN9]~M__3^*~qxuM{R*~qxuD%NH',
  'cruise-seat/ancient-egyptian/rare': 'LGN9]~M__3^*~qxuM{R*~qxuD%NH',
  'cruise-seat/ancient-egyptian/transcendent': 'LGN9]~M__3^*~qxuM{R*~qxuD%NH',
  'cruise-seat/ancient-maya-stone/common': 'LgNle:xa^ixZ%1WVayof~AjGE3bH',
  'cruise-seat/ancient-maya-stone/legendary': 'LgNle:xa^ixZ%1WVayof~AjGE3bH',
  'cruise-seat/ancient-maya-stone/rare': 'LgNle:xa^ixZ%1WVayof~AjGE3bH',
  'cruise-seat/ancient-maya-stone/transcendent': 'LgNle:xa^ixZ%1WVayof~AjGE3bH',
  'cruise-seat/medieval-castle-garderobe/common': 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj[',
  'cruise-seat/medieval-castle-garderobe/legendary': 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj[',
  'cruise-seat/medieval-castle-garderobe/rare': 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj[',
  'cruise-seat/medieval-castle-garderobe/transcendent': 'LOHLrIt7_Nxux]j[oLj@?cj[Mxj[',
  'cruise-seat/prehistoric-stone/common': 'LWGm[LtR*0x^%hV@WBo#yYozMdV@',
  'cruise-seat/prehistoric-stone/legendary': 'LWGm[LtR*0x^%hV@WBo#yYozMdV@',
  'cruise-seat/prehistoric-stone/rare': 'LWGm[LtR*0x^%hV@WBo#yYozMdV@',
  'cruise-seat/prehistoric-stone/transcendent': 'LWGm[LtR*0x^%hV@WBo#yYozMdV@',
  'cruise-seat/victorian-era-wooden-throne/common': 'LsK-I@j]-@xv%NogWAWAt9ogRiRi',
  'cruise-seat/victorian-era-wooden-throne/legendary': 'LsK-I@j]-@xv%NogWAWAt9ogRiRi',
  'cruise-seat/victorian-era-wooden-throne/rare': 'LsK-I@j]-@xv%NogWAWAt9ogRiRi',
  'cruise-seat/victorian-era-wooden-throne/transcendent': 'LsK-I@j]-@xv%NogWAWAt9ogRiRi',
  'turbo-flush/astronaut-zero-gravity/common': 'L8DAfa?a005st6xWIU9Z00I;~9#Q',
  'turbo-flush/astronaut-zero-gravity/legendary': 'L6Hw#d~90NKO1OEOwJsp01EMWF$g',
  'turbo-flush/astronaut-zero-gravity/rare': 'L8B4k5-;01AJs7s%M{IU00M{~7wa',
  'turbo-flush/astronaut-zero-gravity/transcendent': 'L3BDW@=}000ftTx_ITbo00Eh}K;^',
  'turbo-flush/portable-construction-site-cabin/common': 'LHL5I4tS~o^*~poeIoWD~UxZ9HIq',
  'turbo-flush/portable-construction-site-cabin/legendary': 'L5HdZV~7040i08NMDjIpE}s+4@NI',
  'turbo-flush/portable-construction-site-cabin/rare': 'LM9k,N?w%gtR%2%gxut7s*xus.s:',
  'turbo-flush/portable-construction-site-cabin/transcendent': 'L26*B=t600N3tMogRRWB00e;~DR$',
  'turbo-flush/prehistoric-sanitation/common': 'LZIF-*-;%#tR%gofaykC*0azR5az',
  'turbo-flush/prehistoric-sanitation/legendary': 'L6FhUr~TEMRj039cV]xa02E2$%WC',
  'turbo-flush/prehistoric-sanitation/rare': 'L67L=%~q?v%g#N%MnNjFVBj?RPV@',
  'turbo-flush/prehistoric-sanitation/transcendent': 'L36*US?I00D%s+j[R-of00D%~V%M',
  'turbo-flush/roman-public-latrines/common': 'LEMs4f-p=Z-U?GxFV[N_}AV@E*of',
  'turbo-flush/roman-public-latrines/legendary': 'L4GRLv%24,~S049a9u%300S0tTRQ',
  'turbo-flush/roman-public-latrines/rare': 'L57oey~p?v.9z,.7tQjEr9x^RNR4',
  'turbo-flush/roman-public-latrines/transcendent': 'LADvcn?I00jXtRM{9FWB00M{~pMy',
  'turbo-flush/rustic-forest-outhouse/common': 'LUN]d}oJ~V-p%Moff6WB_2t69ZRk',
  'turbo-flush/rustic-forest-outhouse/legendary': 'L7GaHrNIBm~80PR,E3NI0ixYv%EN',
  'turbo-flush/rustic-forest-outhouse/rare': 'L98F7x?b%%%hvx%MoHjYROoziuRh',
  'turbo-flush/rustic-forest-outhouse/transcendent': 'LBKUp6S2ui_3=*xuH[RkyYt6H?M|',
  'turbo-flush/squat/common': 'LaI=1vozrRs?RobExZoMv[jcxooM',
  'turbo-flush/squat/legendary': 'L5J@Bhwt00=_0pR:9wIV00xu_NRj',
  'turbo-flush/squat/rare': 'L8E{na.903-;{H%2Xnay00xZ_1Rj',
  'turbo-flush/squat/transcendent': 'L7LO7$.80x?c{=s:D*af%hjb$kRj',
  'zen-fortress/cyberpunk-dystopian/common': 'LNJb25og~q-;?bafIUt7-;t6IAM{',
  'zen-fortress/cyberpunk-dystopian/legendary': 'LNJb25og~q-;?bafIUt7-;t6IAM{',
  'zen-fortress/cyberpunk-dystopian/rare': 'LNJb25og~q-;?bafIUt7-;t6IAM{',
  'zen-fortress/cyberpunk-dystopian/transcendent': 'LNJb25og~q-;?bafIUt7-;t6IAM{',
  'zen-fortress/dubai/common': 'LHNJtDnh_4_3_3odIUo#t8t7RjMx',
  'zen-fortress/dubai/legendary': 'LHNJtDnh_4_3_3odIUo#t8t7RjMx',
  'zen-fortress/dubai/rare': 'LHNJtDnh_4_3_3odIUo#t8t7RjMx',
  'zen-fortress/dubai/transcendent': 'LHNJtDnh_4_3_3odIUo#t8t7RjMx',
  'zen-fortress/eco-friendly/common': 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_',
  'zen-fortress/eco-friendly/legendary': 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_',
  'zen-fortress/eco-friendly/rare': 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_',
  'zen-fortress/eco-friendly/transcendent': 'LDK_LH%M%%.8?bWBNGozyYt7Q,M_',
  'zen-fortress/futuristic-sci-fi-vacuum/common': 'LAJRF1~qDV$-^,ITxaj1I0xby6M{',
  'zen-fortress/futuristic-sci-fi-vacuum/legendary': 'LAJRF1~qDV$-^,ITxaj1I0xby6M{',
  'zen-fortress/futuristic-sci-fi-vacuum/rare': 'LAJRF1~qDV$-^,ITxaj1I0xby6M{',
  'zen-fortress/futuristic-sci-fi-vacuum/transcendent': 'LAJRF1~qDV$-^,ITxaj1I0xby6M{',
  'zen-fortress/renaissance-chaise/common': 'LmN,bwWB~p?H%MWBaext-;ofIVWB',
  'zen-fortress/renaissance-chaise/legendary': 'LmN,bwWB~p?H%MWBaext-;ofIVWB',
  'zen-fortress/renaissance-chaise/rare': 'LmN,bwWB~p?H%MWBaext-;ofIVWB',
  'zen-fortress/renaissance-chaise/transcendent': 'LmN,bwWB~p?H%MWBaext-;ofIVWB',
}

export const MYSTERY_BOX_BLURHASHES: Partial<Record<NFTRarity, string>> = {
  common: 'LCGZ@eo58]=%-ss;V[S0#es;E?NF',
  rare: 'L38|em0K8@^*1-$*DQOU=8kBy2M|',
  legendary: 'LNFgh^rx52%2%3jcRlj=EDoc$[R+',
  transcendent: 'L5FzhY$p00=kaDoM$%WFqvs;GSIm',
}

export function getNftBlurhash(type: NFTType, name: string, rarity: NFTRarity): string | undefined {
  return NFT_BLURHASHES[`${type}/${name}/${rarity}`]
}

export function getMysteryBoxBlurhash(rarity: NFTRarity): string | undefined {
  return MYSTERY_BOX_BLURHASHES[rarity]
}
