import { StyleSheet } from 'react-native';
import { colors, typography } from '../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    paddingTop: 60,
  },
  title: {
    ...typography.title,
    color: colors.title,
  },
  description: {
    ...typography.description,
    color: colors.text,
    marginBottom: 24,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
    alignItems: 'center',
  },
  selectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  assetSlot: {
    width: 140,
    height: 180,
  },
  selectedAsset: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  assetImage: {
    width: '100%',
    height: 140,
  },
  assetLabel: {
    padding: 12,
    fontSize: 14,
    fontWeight: '600',
    color: colors.title,
    textAlign: 'center',
  },
  tierBadgeMini: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  chillBadgeMini: {
    backgroundColor: '#94a3b8',
  },
  nitroBadgeMini: {
    backgroundColor: '#f59e0b',
  },
  omegaBadgeMini: {
    backgroundColor: '#8b5cf6',
  },
  'cruise-seatBadgeMini': {
    backgroundColor: '#94a3b8',
  },
  'turbo-flushBadgeMini': {
    backgroundColor: '#f59e0b',
  },
  'zen-fortressBadgeMini': {
    backgroundColor: '#8b5cf6',
  },
  tierBadgeMiniText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  emptySlot: {
    width: '100%',
    height: '100%',
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1d5db',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusIcon: {
    fontSize: 40,
    color: '#d1d5db',
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 12,
    color: colors.text,
    textAlign: 'center',
  },
  combineIcon: {
    fontSize: 32,
    color: colors.title,
    marginHorizontal: 24,
    fontWeight: '600',
  },
  breedButton: {
    backgroundColor: colors.buttonPrimary,
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 12,
    marginTop: 20,
  },
  breedButtonDisabled: {
    backgroundColor: '#d1d5db',
    opacity: 0.6,
  },
  breedButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  resultContainer: {
    alignItems: 'center',
    marginBottom: 40,
    width: '100%',
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.title,
    marginBottom: 24,
  },
  resultCard: {
    width: '90%',
    maxWidth: 320,
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultImageContainer: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#f3f4f6',
    position: 'relative',
  },
  resultImage: {
    width: '100%',
    height: '100%',
  },
  levelBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#3b82f6',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  levelBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  tierBadge: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  chillBadge: {
    backgroundColor: '#94a3b8',
  },
  nitroBadge: {
    backgroundColor: '#f59e0b',
  },
  omegaBadge: {
    backgroundColor: '#8b5cf6',
  },
  'cruise-seatBadge': {
    backgroundColor: '#94a3b8',
  },
  'turbo-flushBadge': {
    backgroundColor: '#f59e0b',
  },
  'zen-fortressBadge': {
    backgroundColor: '#8b5cf6',
  },
  tierBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  rarityBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  commonBadge: {
    backgroundColor: '#94a3b8',
  },
  rareBadge: {
    backgroundColor: '#3b82f6',
  },
  legendaryBadge: {
    backgroundColor: '#f59e0b',
  },
  transcendentBadge: {
    backgroundColor: '#a855f7',
  },
  rarityText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  resultCardContent: {
    padding: 16,
    backgroundColor: '#f9fafb',
  },
  resultLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.title,
    textAlign: 'center',
    marginBottom: 12,
  },
  resultDescription: {
    fontSize: 14,
    color: colors.text,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  resetButton: {
    backgroundColor: colors.buttonPrimary,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
  },
  resetButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  errorText: {
    fontSize: 14,
    color: '#ef4444',
    textAlign: 'center',
    marginTop: 20,
  },
});
