import { StyleSheet } from 'react-native';
import { colors, typography } from '../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    paddingTop: 60,
  },
  title: {
    ...typography.title,
    color: colors.title,
  },
  description: {
    ...typography.description,
    color: colors.text,
    marginBottom: 24,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
    alignItems: 'center',
  },
  selectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  assetSlot: {
    width: 140,
    height: 180,
  },
  selectedAsset: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  assetImage: {
    width: '100%',
    height: 140,
  },
  assetLabel: {
    padding: 12,
    fontSize: 14,
    fontWeight: '600',
    color: colors.title,
    textAlign: 'center',
  },
  emptySlot: {
    width: '100%',
    height: '100%',
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1d5db',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusIcon: {
    fontSize: 40,
    color: '#d1d5db',
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 12,
    color: colors.text,
    textAlign: 'center',
  },
  combineIcon: {
    fontSize: 32,
    color: colors.title,
    marginHorizontal: 24,
    fontWeight: '600',
  },
  breedButton: {
    backgroundColor: colors.button,
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 12,
    marginTop: 20,
  },
  breedButtonDisabled: {
    backgroundColor: '#d1d5db',
    opacity: 0.6,
  },
  breedButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  resultContainer: {
    alignItems: 'center',
    marginBottom: 40,
    width: '100%',
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.title,
    marginBottom: 24,
  },
  resultCard: {
    width: '90%',
    maxWidth: 320,
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultImageContainer: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#f3f4f6',
  },
  resultImage: {
    width: '100%',
    height: '100%',
  },
  resultCardContent: {
    padding: 16,
    backgroundColor: '#f9fafb',
  },
  resultLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.title,
    textAlign: 'center',
    marginBottom: 12,
  },
  resultDescription: {
    fontSize: 14,
    color: colors.text,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  resetButton: {
    backgroundColor: colors.button,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
  },
  resetButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
