import { StyleSheet } from 'react-native';
import { colors, fontSizes, fontWeights, radii, spacing } from '@/constants';

export const sortStyles = StyleSheet.create({
  sortContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.base,
    paddingHorizontal: spacing.lg,
  },
  sortLabel: {
    fontSize: fontSizes.md,
    color: colors.text,
    marginRight: 10,
    fontWeight: fontWeights.medium,
  },
  sortControlGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    zIndex: 1000,
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSurface,
    paddingVertical: spacing.sm,
    paddingLeft: spacing.base,
    paddingRight: spacing.md,
    borderTopLeftRadius: radii.md,
    borderBottomLeftRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 100,
    height: 36,
    justifyContent: 'space-between',
  },
  sortButtonText: {
    fontSize: fontSizes.md,
    color: colors.title,
    fontWeight: fontWeights.semibold,
    marginRight: 6,
  },
  sortButtonIcon: {
    fontSize: fontSizes.xs,
    color: colors.text,
  },
  sortOrderButton: {
    backgroundColor: colors.bgSurface,
    paddingHorizontal: 10,
    borderTopRightRadius: radii.md,
    borderBottomRightRadius: radii.md,
    borderWidth: 1,
    borderLeftWidth: 0,
    borderColor: colors.border,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sortOrderIcon: {
    fontSize: fontSizes.base,
    color: colors.title,
    fontWeight: fontWeights.semibold,
  },
  sortMenu: {
    position: 'absolute',
    top: 38,
    left: 0,
    right: 0,
    backgroundColor: colors.bgSurface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1001,
  },
  sortMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: spacing.base,
    borderBottomWidth: 1,
    borderBottomColor: colors.bgLight,
  },
  sortMenuItemActive: {
    backgroundColor: colors.selectionBg,
  },
  sortMenuItemText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  sortMenuItemTextActive: {
    color: colors.buttonPrimary,
    fontWeight: fontWeights.semibold,
  },
});
