import { StyleSheet } from 'react-native';
import { colors } from '@/constants';

export const sortStyles = StyleSheet.create({
  sortContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  sortLabel: {
    fontSize: 14,
    color: colors.text,
    marginRight: 10,
    fontWeight: '500',
  },
  sortControlGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    zIndex: 1000,
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSurface,
    paddingVertical: 8,
    paddingLeft: 16,
    paddingRight: 12,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 100,
    height: 36,
    justifyContent: 'space-between',
  },
  sortButtonText: {
    fontSize: 14,
    color: colors.title,
    fontWeight: '600',
    marginRight: 6,
  },
  sortButtonIcon: {
    fontSize: 10,
    color: colors.text,
  },
  sortOrderButton: {
    backgroundColor: colors.bgSurface,
    paddingHorizontal: 10,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderWidth: 1,
    borderLeftWidth: 0,
    borderColor: colors.border,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sortOrderIcon: {
    fontSize: 16,
    color: colors.title,
    fontWeight: '600',
  },
  sortMenu: {
    position: 'absolute',
    top: 38,
    left: 0,
    right: 0,
    backgroundColor: colors.bgSurface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1001,
  },
  sortMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.bgLight,
  },
  sortMenuItemActive: {
    backgroundColor: colors.selectionBg,
  },
  sortMenuItemText: {
    fontSize: 14,
    color: colors.text,
  },
  sortMenuItemTextActive: {
    color: colors.buttonPrimary,
    fontWeight: '600',
  },
});
